/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zz_hao_jni_JNITest */

#ifndef _Included_zz_hao_jni_JNITest
#define _Included_zz_hao_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zz_hao_jni_JNITest
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zz_hao_jni_JNITest_test
  (JNIEnv*  env, jobject jobj){
    char*  text = "hello，调用JNI成功~";
    return  (*env)-> NewStringUTF(env,text);
};

#ifdef __cplusplus
}
#endif
#endif
